# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 260, 351, 171))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_AccountsBrowser = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_AccountsBrowser.setGeometry(QtCore.QRect(260, 20, 75, 23))
        self.pushButton_AccountsBrowser.setObjectName("pushButton_AccountsBrowser")
        self.lineEdit_Accounts = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Accounts.setGeometry(QtCore.QRect(20, 20, 231, 31))
        self.lineEdit_Accounts.setObjectName("lineEdit_Accounts")
        self.listView_Accounts = QtWidgets.QListView(self.groupBox)
        self.listView_Accounts.setGeometry(QtCore.QRect(20, 60, 311, 181))
        self.listView_Accounts.setObjectName("listView_Accounts")
        self.groupBox_Proxies = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Proxies.setGeometry(QtCore.QRect(420, 260, 351, 251))
        self.groupBox_Proxies.setObjectName("groupBox_Proxies")
        self.pushButton_Proxies_Browser = QtWidgets.QPushButton(self.groupBox_Proxies)
        self.pushButton_Proxies_Browser.setGeometry(QtCore.QRect(260, 20, 75, 23))
        self.pushButton_Proxies_Browser.setObjectName("pushButton_Proxies_Browser")
        self.lineEdit_Proxies = QtWidgets.QLineEdit(self.groupBox_Proxies)
        self.lineEdit_Proxies.setGeometry(QtCore.QRect(20, 20, 231, 31))
        self.lineEdit_Proxies.setObjectName("lineEdit_Proxies")
        self.listView_Proxies = QtWidgets.QListView(self.groupBox_Proxies)
        self.listView_Proxies.setGeometry(QtCore.QRect(20, 60, 311, 111))
        self.listView_Proxies.setObjectName("listView_Proxies")
        self.spinBox_PerProxyRequestLimit = QtWidgets.QSpinBox(self.groupBox_Proxies)
        self.spinBox_PerProxyRequestLimit.setGeometry(QtCore.QRect(170, 190, 42, 22))
        self.spinBox_PerProxyRequestLimit.setObjectName("spinBox_PerProxyRequestLimit")
        self.label_22 = QtWidgets.QLabel(self.groupBox_Proxies)
        self.label_22.setGeometry(QtCore.QRect(20, 220, 71, 16))
        self.label_22.setObjectName("label_22")
        self.label = QtWidgets.QLabel(self.groupBox_Proxies)
        self.label.setGeometry(QtCore.QRect(20, 190, 151, 16))
        self.label.setObjectName("label")
        self.radioButton_ProxyTypeHttp = QtWidgets.QRadioButton(self.groupBox_Proxies)
        self.radioButton_ProxyTypeHttp.setGeometry(QtCore.QRect(170, 220, 86, 16))
        self.radioButton_ProxyTypeHttp.setObjectName("radioButton_ProxyTypeHttp")
        self.radioButton_ProxyTypeSocks5 = QtWidgets.QRadioButton(self.groupBox_Proxies)
        self.radioButton_ProxyTypeSocks5.setGeometry(QtCore.QRect(230, 220, 86, 16))
        self.radioButton_ProxyTypeSocks5.setObjectName("radioButton_ProxyTypeSocks5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 440, 351, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_Pause = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Pause.setGeometry(QtCore.QRect(130, 90, 75, 23))
        self.pushButton_Pause.setObjectName("pushButton_Pause")
        self.pushButton_Cancel = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(240, 90, 75, 23))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.pushButton_Start = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Start.setGeometry(QtCore.QRect(20, 90, 75, 23))
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.label_21.setObjectName("label_21")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 81, 16))
        self.label_3.setObjectName("label_3")
        self.spinBox_MultiThreads = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_MultiThreads.setGeometry(QtCore.QRect(110, 60, 42, 22))
        self.spinBox_MultiThreads.setObjectName("spinBox_MultiThreads")
        self.spinBox_Timeout = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_Timeout.setGeometry(QtCore.QRect(270, 30, 42, 22))
        self.spinBox_Timeout.setObjectName("spinBox_Timeout")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_23.setObjectName("label_23")
        self.lineEdit_db = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_db.setGeometry(QtCore.QRect(110, 30, 61, 20))
        self.lineEdit_db.setObjectName("lineEdit_db")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(180, 60, 101, 16))
        self.label_24.setObjectName("label_24")
        self.spinBox_Interval = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_Interval.setGeometry(QtCore.QRect(270, 60, 42, 22))
        self.spinBox_Interval.setObjectName("spinBox_Interval")
        self.groupBox_Arguments = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Arguments.setGeometry(QtCore.QRect(30, 10, 741, 241))
        self.groupBox_Arguments.setObjectName("groupBox_Arguments")
        self.label_4 = QtWidgets.QLabel(self.groupBox_Arguments)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 54, 12))
        self.label_4.setObjectName("label_4")
        self.lineEdit_Url = QtWidgets.QLineEdit(self.groupBox_Arguments)
        self.lineEdit_Url.setGeometry(QtCore.QRect(80, 20, 641, 20))
        self.lineEdit_Url.setObjectName("lineEdit_Url")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_Arguments)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 50, 161, 80))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_6.setObjectName("label_6")
        self.lineEdit_Argv1Key = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_Argv1Key.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.lineEdit_Argv1Key.setObjectName("lineEdit_Argv1Key")
        self.lineEdit_Argv1Value = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_Argv1Value.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.lineEdit_Argv1Value.setObjectName("lineEdit_Argv1Value")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_Arguments)
        self.groupBox_6.setGeometry(QtCore.QRect(200, 50, 161, 80))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_8.setObjectName("label_8")
        self.lineEdit_Argv2Key = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Argv2Key.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.lineEdit_Argv2Key.setObjectName("lineEdit_Argv2Key")
        self.lineEdit_Argv2Value = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Argv2Value.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.lineEdit_Argv2Value.setObjectName("lineEdit_Argv2Value")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_Arguments)
        self.groupBox_7.setGeometry(QtCore.QRect(380, 50, 161, 80))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_10.setObjectName("label_10")
        self.lineEdit_Argv3Key = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_Argv3Key.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.lineEdit_Argv3Key.setObjectName("lineEdit_Argv3Key")
        self.lineEdit_Argv3Value = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_Argv3Value.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.lineEdit_Argv3Value.setObjectName("lineEdit_Argv3Value")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_Arguments)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 150, 161, 80))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_11 = QtWidgets.QLabel(self.groupBox_8)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_8)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_12.setObjectName("label_12")
        self.lineEdit_Argv5Key = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_Argv5Key.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.lineEdit_Argv5Key.setObjectName("lineEdit_Argv5Key")
        self.lineEdit_Argv5Value = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_Argv5Value.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.lineEdit_Argv5Value.setObjectName("lineEdit_Argv5Value")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_Arguments)
        self.groupBox_9.setGeometry(QtCore.QRect(200, 150, 161, 80))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_13 = QtWidgets.QLabel(self.groupBox_9)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_9)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_14.setObjectName("label_14")
        self.lineEdit_Argv6Key = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_Argv6Key.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.lineEdit_Argv6Key.setObjectName("lineEdit_Argv6Key")
        self.lineEdit_Argv6Value = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_Argv6Value.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.lineEdit_Argv6Value.setObjectName("lineEdit_Argv6Value")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_Arguments)
        self.groupBox_10.setGeometry(QtCore.QRect(380, 150, 161, 80))
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_10)
        self.label_16.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_16.setObjectName("label_16")
        self.lineEdit_Argv7Key = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_Argv7Key.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.lineEdit_Argv7Key.setObjectName("lineEdit_Argv7Key")
        self.lineEdit_Argv7Value = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_Argv7Value.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.lineEdit_Argv7Value.setObjectName("lineEdit_Argv7Value")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_Arguments)
        self.groupBox_11.setGeometry(QtCore.QRect(560, 150, 161, 80))
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_17 = QtWidgets.QLabel(self.groupBox_11)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_11)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_18.setObjectName("label_18")
        self.lineEdit_Argv8Key = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_Argv8Key.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.lineEdit_Argv8Key.setObjectName("lineEdit_Argv8Key")
        self.lineEdit_Argv8Value = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_Argv8Value.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.lineEdit_Argv8Value.setObjectName("lineEdit_Argv8Value")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_Arguments)
        self.groupBox_12.setGeometry(QtCore.QRect(560, 50, 161, 80))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_19 = QtWidgets.QLabel(self.groupBox_12)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_12)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_20.setObjectName("label_20")
        self.lineEdit_Argv4Key = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_Argv4Key.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.lineEdit_Argv4Key.setObjectName("lineEdit_Argv4Key")
        self.lineEdit_Argv4Value = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_Argv4Value.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.lineEdit_Argv4Value.setObjectName("lineEdit_Argv4Value")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 550, 131, 16))
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(630, 550, 141, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lineEdit_CurrentAccountsLine = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CurrentAccountsLine.setGeometry(QtCore.QRect(560, 550, 41, 20))
        self.lineEdit_CurrentAccountsLine.setObjectName("lineEdit_CurrentAccountsLine")
        self.checkBox_UseProxie = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_UseProxie.setGeometry(QtCore.QRect(440, 520, 91, 16))
        self.checkBox_UseProxie.setObjectName("checkBox_UseProxie")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Profile = QtWidgets.QAction(MainWindow)
        self.actionLoad_Profile.setObjectName("actionLoad_Profile")
        self.actionSave_Profile = QtWidgets.QAction(MainWindow)
        self.actionSave_Profile.setObjectName("actionSave_Profile")
        self.menuFile.addAction(self.actionLoad_Profile)
        self.menuFile.addAction(self.actionSave_Profile)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ryerson University Burst"))
        self.groupBox.setTitle(_translate("MainWindow", "Accounts"))
        self.pushButton_AccountsBrowser.setText(_translate("MainWindow", "Browser"))
        self.groupBox_Proxies.setTitle(_translate("MainWindow", "Proxies"))
        self.pushButton_Proxies_Browser.setText(_translate("MainWindow", "Browser"))
        self.label_22.setText(_translate("MainWindow", "Proxy Type:"))
        self.label.setText(_translate("MainWindow", "Per Proxy Request Limit:"))
        self.radioButton_ProxyTypeHttp.setText(_translate("MainWindow", "Http"))
        self.radioButton_ProxyTypeSocks5.setText(_translate("MainWindow", "Socks5"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Control"))
        self.pushButton_Pause.setText(_translate("MainWindow", "Pause"))
        self.pushButton_Cancel.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.label_21.setText(_translate("MainWindow", "Multi Threads:"))
        self.label_3.setText(_translate("MainWindow", "Timeout(Sec):"))
        self.label_23.setText(_translate("MainWindow", "Sqlite3 DB:"))
        self.label_24.setText(_translate("MainWindow", "Interval(Sec):"))
        self.groupBox_Arguments.setTitle(_translate("MainWindow", "Request Arguments"))
        self.label_4.setText(_translate("MainWindow", "Url:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Argv[1]"))
        self.label_5.setText(_translate("MainWindow", "Key:"))
        self.label_6.setText(_translate("MainWindow", "Value:"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Argv[2]"))
        self.label_7.setText(_translate("MainWindow", "Key:"))
        self.label_8.setText(_translate("MainWindow", "Value:"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Argv[3]"))
        self.label_9.setText(_translate("MainWindow", "Key:"))
        self.label_10.setText(_translate("MainWindow", "Value:"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Argv[5]"))
        self.label_11.setText(_translate("MainWindow", "Key:"))
        self.label_12.setText(_translate("MainWindow", "Value:"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Argv[6]"))
        self.label_13.setText(_translate("MainWindow", "Key:"))
        self.label_14.setText(_translate("MainWindow", "Value:"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Argv[7]"))
        self.label_15.setText(_translate("MainWindow", "Key:"))
        self.label_16.setText(_translate("MainWindow", "Value:"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Argv[8]"))
        self.label_17.setText(_translate("MainWindow", "Key:"))
        self.label_18.setText(_translate("MainWindow", "Value:"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Argv[4]"))
        self.label_19.setText(_translate("MainWindow", "Key:"))
        self.label_20.setText(_translate("MainWindow", "Value:"))
        self.label_2.setText(_translate("MainWindow", "Current Accounts Line:"))
        self.checkBox_UseProxie.setText(_translate("MainWindow", "Proxy_Enable"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Profile.setText(_translate("MainWindow", "Load Profile"))
        self.actionSave_Profile.setText(_translate("MainWindow", "Save Profile"))
